name: compass
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - pandas
  - requests
  - bokeh
  - jupyterlab
  - lxml
  - panel
  - tqdm
  - ipykernel
  - ipywidgets
  - pip
  - pip:
      - pyldavis

