name: compass
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - bokeh
  - gensim
  - ipykernel
  - ipywidgets
  - jupyterlab
  - lxml
  - matplotlib
  - matplotlib-venn
  - nltk
  - numpy
  - pandas
  - panel
  - pip
  - requests
  - tqdm
  - umap-learn
  - pip:
      - pyldavis
  
