name: compass
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bokeh
  - gensim
  - ipykernel
  - ipywidgets
  - jupyterlab
  - lxml
  - matplotlib
  - matplotlib-venn
  - nltk
  - numpy
  - pandas
  - panel
  - pip
  - pyldavis
  - requests
  - scipy=1.12
  # gensim 4.3.2 is incompatible with scipy 1.13 or higher
  - tqdm
  - umap-learn
  - networkx

  
